version: "3"

services:
  jupyter:
    container_name: jupyter
    image: jupyter
    ports:
      - "8888:8888"
      - "2222:22"
    volumes:
      - ~/.ssh/authorized_keys:/authorized_keys
      - ./home:/root